settings:
  backoff_multiplier: 2
  buffer_size: 8
  cpu_buffer_duration_sec: 3.0
  cpu_buffer_enabled: true
  decoder_preference: auto
  gpu_id: 0
  log_base_path: ./logs
  output_format: NV12
  retry_max_attempts: 0
streams:
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 1
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 2
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 3
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 4
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 5
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 6
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 7
- file: /home/omar/work/tenssort_inference/tenssort_inference/videos/vid5.mp4
  fps: 30
  loop: true
  name: Stream 8
